import { AudioTrackMeta, DspParameters, PatchNode, PatchCable } from '../types/dsp';

export const BUILT_IN_TRACKS: AudioTrackMeta[] = [
  {
    id: 'ziaa-membrane',
    title: 'Room-Memory Membrane Study (Rev 3.2)',
    artist: 'ZIAA Acoustic Research Lab',
    type: 'archive',
    duration: 180,
    bpm: 124,
    key: 'D# Minor',
    sampleRate: 48000,
    description: 'Thin concentric aluminium resonator, contact piezo pickups, non-linear harmonic feedback & spatial room reflections.',
    speculativeRef: 'ZIAA-P-0128',
  },
  {
    id: 'glitch-breaks',
    title: 'Cybernetic Poly-Rhythm & Acid Glitch',
    artist: 'TouchDesigner DSP Collective',
    type: 'archive',
    duration: 160,
    bpm: 140,
    key: 'F Phrygian',
    sampleRate: 48000,
    description: 'Ultra-dense breakcore micro-transients, syncopated 303 acid basslines, modular comb filter bursts & spatial delay.',
    speculativeRef: 'TD-IDM-09',
  },
  {
    id: 'psy-trance',
    title: 'Hyperspace Psy-Trance & Torus Vector',
    artist: 'Aether-Spectrum Systems',
    type: 'archive',
    duration: 210,
    bpm: 144,
    key: 'A Minor',
    sampleRate: 48000,
    description: 'Rolling sub-bass triplets, harmonic resonance sweeps, psychotropic frequency dispersion and stereo Haas expansion.',
    speculativeRef: 'MAX-DSP-88',
  },
  {
    id: 'ambient-drone',
    title: 'Deep Spectral Cartography & Shimmer',
    artist: 'Zazie Institute of Applied Anomalies',
    type: 'archive',
    duration: 240,
    bpm: 72,
    key: 'C# Lydian',
    sampleRate: 48000,
    description: 'Aetheric generative drone swells, granular choral shimmer, microtonal beatings and sub-acoustic room resonance.',
    speculativeRef: 'ZIAA-I-0024',
  },
];

export const DEFAULT_DSP_PARAMS: DspParameters = {
  masterVolume: 0.85,
  playbackRate: 1.0,
  loop: true,
  reverse: false,

  filterType: 'lowpass',
  filterCutoff: 12500,
  filterResonance: 3.2,
  filterDrive: 1.8,

  stereoWidth: 1.25,
  pitchShift: 0,
  bitcrushBits: 14,
  bitcrushRate: 1.0,
  reverbWet: 0.35,
  reverbDecay: 3.4,
  reverbDamp: 0.45,
  delayTime: 0.32,
  delayFeedback: 0.42,
  delayWet: 0.28,
  granularStutter: 0.0,
  tapeFlutter: 0.15,
  subHarmonic: 0.4,

  contourDensity: 24,
  elevationScale: 1.4,
  spatiotemporalPersistence: 0.82,

  lfo1Rate: 0.45,
  lfo1Shape: 'sine',
  lfo1Depth: 0.65,
  lfo2Rate: 2.8,
  lfo2Shape: 'triangle',
  lfo2Depth: 0.35,

  envelopeAttack: 0.05,
  envelopeRelease: 0.45,
  envelopeSensitivity: 2.2,

  xyPadX: 0.0,
  xyPadY: 0.0,

  bloom: 0.68,
  feedbackTrails: 0.82,
  chromaticAberration: 0.45,
  cameraFov: 75,
  particleCount: 12000,
  glitchIntensity: 0.25,
  rotationSpeed: 0.65,
  reactivity: 1.45,
  wireframe: false,
  colorPalette: 'acid-neon',
};

export const INITIAL_PATCH_NODES: PatchNode[] = [
  {
    id: 'node-audio-in',
    type: 'audio-in',
    title: 'adc~ [audio-input]',
    category: 'audio',
    x: 40,
    y: 60,
    inputs: [],
    outputs: [
      { id: 'sig-l', label: 'L Out', type: 'audio' },
      { id: 'sig-r', label: 'R Out', type: 'audio' },
      { id: 'sig-sum', label: 'Sum Out', type: 'audio' },
    ],
    params: {
      source: 'archive',
      gain: 0.85,
      pitch: 0,
    },
  },
  {
    id: 'node-fft',
    type: 'fft-splitter',
    title: 'fft~ [spectral-analyzer]',
    category: 'audio',
    x: 290,
    y: 50,
    inputs: [
      { id: 'in', label: 'Audio In', type: 'audio' },
    ],
    outputs: [
      { id: 'sub', label: 'Sub (20-60Hz)', type: 'control' },
      { id: 'bass', label: 'Bass (60-250Hz)', type: 'control' },
      { id: 'mid', label: 'Mid (250-2kHz)', type: 'control' },
      { id: 'high', label: 'Treble (2k-20kHz)', type: 'control' },
      { id: 'centroid', label: 'Centroid (Hz)', type: 'control' },
      { id: 'beat', label: 'Beat Pulse', type: 'control' },
    ],
    params: {
      fftSize: 2048,
      smoothing: 0.82,
    },
  },
  {
    id: 'node-filter',
    type: 'spectral-filter',
    title: 'biquad~ [state-variable]',
    category: 'dsp',
    x: 290,
    y: 320,
    inputs: [
      { id: 'audio-in', label: 'Sig In', type: 'audio' },
      { id: 'mod-cutoff', label: 'Mod Cutoff', type: 'control' },
      { id: 'mod-res', label: 'Mod Res', type: 'control' },
    ],
    outputs: [
      { id: 'filtered-out', label: 'Sig Out', type: 'audio' },
    ],
    params: {
      type: 'lowpass',
      cutoff: 12500,
      resonance: 3.2,
      drive: 1.8,
    },
  },
  {
    id: 'node-lfo',
    type: 'lfo-matrix',
    title: 'lfo.matrix [4-ch mod]',
    category: 'mod',
    x: 40,
    y: 340,
    inputs: [
      { id: 'sync', label: 'Clock Sync', type: 'control' },
    ],
    outputs: [
      { id: 'lfo1', label: 'LFO 1 (Sine)', type: 'control' },
      { id: 'lfo2', label: 'LFO 2 (Tri)', type: 'control' },
      { id: 'lfo3', label: 'LFO 3 (Saw)', type: 'control' },
    ],
    params: {
      rate1: 0.45,
      rate2: 2.8,
      depth: 0.65,
    },
  },
  {
    id: 'node-dsp-console',
    type: 'hallucination-dsp',
    title: 'dsp.hallucinate~ [psy-fx]',
    category: 'dsp',
    x: 560,
    y: 280,
    inputs: [
      { id: 'audio-in', label: 'Sig In', type: 'audio' },
      { id: 'mod-warp', label: 'Mod Warp', type: 'control' },
      { id: 'mod-stutter', label: 'Mod Stutter', type: 'control' },
    ],
    outputs: [
      { id: 'audio-out', label: 'Sig Out', type: 'audio' },
    ],
    params: {
      haasWidth: 1.25,
      bitcrush: 14,
      flutter: 0.15,
      subHarmonic: 0.4,
    },
  },
  {
    id: 'node-reverb',
    type: 'reverb-space',
    title: 'freeverb~ [modal room]',
    category: 'dsp',
    x: 820,
    y: 310,
    inputs: [
      { id: 'audio-in', label: 'Audio In', type: 'audio' },
      { id: 'mod-decay', label: 'Mod Decay', type: 'control' },
    ],
    outputs: [
      { id: 'audio-out', label: 'Wet Out', type: 'audio' },
    ],
    params: {
      decay: 3.4,
      damp: 0.45,
      wet: 0.35,
    },
  },
  {
    id: 'node-master',
    type: 'master-out',
    title: 'dac~ [master-output]',
    category: 'out',
    x: 1080,
    y: 330,
    inputs: [
      { id: 'audio-in', label: 'L/R In', type: 'audio' },
      { id: 'limiter', label: 'Limiter Ceil', type: 'control' },
    ],
    outputs: [],
    params: {
      volume: 0.85,
      limiter: true,
      sampleRate: '48kHz',
    },
  },
  {
    id: 'node-raymarcher',
    type: 'psy-raymarcher',
    title: 'raymarcher.TOP [volumetric]',
    category: 'visual',
    x: 580,
    y: 40,
    inputs: [
      { id: 'react-bass', label: 'Bass Deform', type: 'control' },
      { id: 'react-beat', label: 'Beat Pulse', type: 'control' },
      { id: 'react-mid', label: 'Harmonic Twist', type: 'control' },
    ],
    outputs: [
      { id: 'texture-out', label: 'Render Out', type: 'texture' },
    ],
    params: {
      fov: 75,
      bloom: 0.68,
      trails: 0.82,
      chromatic: 0.45,
    },
  },
  {
    id: 'node-cartography',
    type: 'spatial-carto',
    title: 'carto.TOP [spatiotemporal]',
    category: 'visual',
    x: 850,
    y: 50,
    inputs: [
      { id: 'fft-feed', label: 'FFT Data', type: 'control' },
      { id: 'mod-density', label: 'Iso Density', type: 'control' },
    ],
    outputs: [
      { id: 'texture-out', label: 'Mesh Out', type: 'texture' },
    ],
    params: {
      elevation: 1.4,
      density: 24,
      persistence: 0.82,
    },
  },
];

export const INITIAL_PATCH_CABLES: PatchCable[] = [
  // Audio signal path
  { id: 'c1', fromNodeId: 'node-audio-in', fromSocketId: 'sig-sum', toNodeId: 'node-fft', toSocketId: 'in', color: '#00f0ff' },
  { id: 'c2', fromNodeId: 'node-audio-in', fromSocketId: 'sig-sum', toNodeId: 'node-filter', toSocketId: 'audio-in', color: '#00f0ff' },
  { id: 'c3', fromNodeId: 'node-filter', fromSocketId: 'filtered-out', toNodeId: 'node-dsp-console', toSocketId: 'audio-in', color: '#00f0ff' },
  { id: 'c4', fromNodeId: 'node-dsp-console', fromSocketId: 'audio-out', toNodeId: 'node-reverb', toSocketId: 'audio-in', color: '#00f0ff' },
  { id: 'c5', fromNodeId: 'node-reverb', fromSocketId: 'audio-out', toNodeId: 'node-master', toSocketId: 'audio-in', color: '#00f0ff' },

  // Modulation & control paths
  { id: 'c6', fromNodeId: 'node-fft', fromSocketId: 'bass', toNodeId: 'node-raymarcher', toSocketId: 'react-bass', color: '#ff0055' },
  { id: 'c7', fromNodeId: 'node-fft', fromSocketId: 'beat', toNodeId: 'node-raymarcher', toSocketId: 'react-beat', color: '#ffaa00' },
  { id: 'c8', fromNodeId: 'node-fft', fromSocketId: 'mid', toNodeId: 'node-raymarcher', toSocketId: 'react-mid', color: '#39ff14' },
  { id: 'c9', fromNodeId: 'node-fft', fromSocketId: 'centroid', toNodeId: 'node-cartography', toSocketId: 'fft-feed', color: '#9d4edd' },
  { id: 'c10', fromNodeId: 'node-lfo', fromSocketId: 'lfo1', toNodeId: 'node-filter', toSocketId: 'mod-cutoff', color: '#ff0055' },
  { id: 'c11', fromNodeId: 'node-lfo', fromSocketId: 'lfo2', toNodeId: 'node-dsp-console', toSocketId: 'mod-warp', color: '#ff0055' },
];
